# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CompanyRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, company_img_url: str=None, about_us: str=None, website_link: str=None):  # noqa: E501
        """CompanyRequest - a model defined in Swagger

        :param name: The name of this CompanyRequest.  # noqa: E501
        :type name: str
        :param company_img_url: The company_img_url of this CompanyRequest.  # noqa: E501
        :type company_img_url: str
        :param about_us: The about_us of this CompanyRequest.  # noqa: E501
        :type about_us: str
        :param website_link: The website_link of this CompanyRequest.  # noqa: E501
        :type website_link: str
        """
        self.swagger_types = {
            'name': str,
            'company_img_url': str,
            'about_us': str,
            'website_link': str
        }

        self.attribute_map = {
            'name': 'name',
            'company_img_url': 'company_img_url',
            'about_us': 'about_us',
            'website_link': 'website_link'
        }
        self._name = name
        self._company_img_url = company_img_url
        self._about_us = about_us
        self._website_link = website_link

    @classmethod
    def from_dict(cls, dikt) -> 'CompanyRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Company_Request of this CompanyRequest.  # noqa: E501
        :rtype: CompanyRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this CompanyRequest.


        :return: The name of this CompanyRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CompanyRequest.


        :param name: The name of this CompanyRequest.
        :type name: str
        """

        self._name = name

    @property
    def company_img_url(self) -> str:
        """Gets the company_img_url of this CompanyRequest.


        :return: The company_img_url of this CompanyRequest.
        :rtype: str
        """
        return self._company_img_url

    @company_img_url.setter
    def company_img_url(self, company_img_url: str):
        """Sets the company_img_url of this CompanyRequest.


        :param company_img_url: The company_img_url of this CompanyRequest.
        :type company_img_url: str
        """

        self._company_img_url = company_img_url

    @property
    def about_us(self) -> str:
        """Gets the about_us of this CompanyRequest.


        :return: The about_us of this CompanyRequest.
        :rtype: str
        """
        return self._about_us

    @about_us.setter
    def about_us(self, about_us: str):
        """Sets the about_us of this CompanyRequest.


        :param about_us: The about_us of this CompanyRequest.
        :type about_us: str
        """

        self._about_us = about_us

    @property
    def website_link(self) -> str:
        """Gets the website_link of this CompanyRequest.


        :return: The website_link of this CompanyRequest.
        :rtype: str
        """
        return self._website_link

    @website_link.setter
    def website_link(self, website_link: str):
        """Sets the website_link of this CompanyRequest.


        :param website_link: The website_link of this CompanyRequest.
        :type website_link: str
        """

        self._website_link = website_link
