# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Orders(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, cus_uid: str=None, order_date_time: str=None, p_uid: str=None, product_img_url: str=None, company_name: str=None, company_img_url: str=None, message: str=None):  # noqa: E501
        """Orders - a model defined in Swagger

        :param id: The id of this Orders.  # noqa: E501
        :type id: str
        :param cus_uid: The cus_uid of this Orders.  # noqa: E501
        :type cus_uid: str
        :param order_date_time: The order_date_time of this Orders.  # noqa: E501
        :type order_date_time: datetime
        :param p_uid: The p_uid of this Orders.  # noqa: E501
        :type p_uid: str
        :param product_img_url: The product_img_url of this Orders.  # noqa: E501
        :type product_img_url: str
        :param company_name: The company_name of this Orders.  # noqa: E501
        :type company_name: str
        :param company_img_url: The company_img_url of this Orders.  # noqa: E501
        :type company_img_url: str
        :param message: The message of this Orders.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'id': str,
            'cus_uid': str,
            'order_date_time': str,
            'p_uid': str,
            'product_img_url': str,
            'company_name': str,
            'company_img_url': str,
            'message': str
        }

        self.attribute_map = {
            'id': 'id',
            'cus_uid': 'cus_uid',
            'order_date_time': 'order_date_time',
            'p_uid': 'p_uid',
            'product_img_url': 'product_img_url',
            'company_name': 'company_name',
            'company_img_url': 'company_img_url',
            'message': 'message'
        }
        self._id = id
        self._cus_uid = cus_uid
        self._order_date_time = order_date_time
        self._p_uid = p_uid
        self._product_img_url = product_img_url
        self._company_name = company_name
        self._company_img_url = company_img_url
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Orders':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Orders of this Orders.  # noqa: E501
        :rtype: Orders
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Orders.


        :return: The id of this Orders.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Orders.


        :param id: The id of this Orders.
        :type id: str
        """

        self._id = id

    @property
    def cus_uid(self) -> str:
        """Gets the cus_uid of this Orders.

        customer id of the one who placed the order  # noqa: E501

        :return: The cus_uid of this Orders.
        :rtype: str
        """
        return self._cus_uid

    @cus_uid.setter
    def cus_uid(self, cus_uid: str):
        """Sets the cus_uid of this Orders.

        customer id of the one who placed the order  # noqa: E501

        :param cus_uid: The cus_uid of this Orders.
        :type cus_uid: str
        """

        self._cus_uid = cus_uid

    @property
    def order_date_time(self) -> str:
        """Gets the order_date_time of this Orders.


        :return: The order_date_time of this Orders.
        :rtype: datetime
        """
        return self._order_date_time

    @order_date_time.setter
    def order_date_time(self, order_date_time: str):
        """Sets the order_date_time of this Orders.


        :param order_date_time: The order_date_time of this Orders.
        :type order_date_time: datetime
        """

        self._order_date_time = order_date_time

    @property
    def p_uid(self) -> str:
        """Gets the p_uid of this Orders.

        product id of the product ordered  # noqa: E501

        :return: The p_uid of this Orders.
        :rtype: str
        """
        return self._p_uid

    @p_uid.setter
    def p_uid(self, p_uid: str):
        """Sets the p_uid of this Orders.

        product id of the product ordered  # noqa: E501

        :param p_uid: The p_uid of this Orders.
        :type p_uid: str
        """

        self._p_uid = p_uid

    @property
    def product_img_url(self) -> str:
        """Gets the product_img_url of this Orders.


        :return: The product_img_url of this Orders.
        :rtype: str
        """
        return self._product_img_url

    @product_img_url.setter
    def product_img_url(self, product_img_url: str):
        """Sets the product_img_url of this Orders.


        :param product_img_url: The product_img_url of this Orders.
        :type product_img_url: str
        """

        self._product_img_url = product_img_url

    @property
    def company_name(self) -> str:
        """Gets the company_name of this Orders.


        :return: The company_name of this Orders.
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name: str):
        """Sets the company_name of this Orders.


        :param company_name: The company_name of this Orders.
        :type company_name: str
        """

        self._company_name = company_name

    @property
    def company_img_url(self) -> str:
        """Gets the company_img_url of this Orders.


        :return: The company_img_url of this Orders.
        :rtype: str
        """
        return self._company_img_url

    @company_img_url.setter
    def company_img_url(self, company_img_url: str):
        """Sets the company_img_url of this Orders.


        :param company_img_url: The company_img_url of this Orders.
        :type company_img_url: str
        """

        self._company_img_url = company_img_url

    @property
    def message(self) -> str:
        """Gets the message of this Orders.

        email communication b/w customer and contractor  # noqa: E501

        :return: The message of this Orders.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Orders.

        email communication b/w customer and contractor  # noqa: E501

        :param message: The message of this Orders.
        :type message: str
        """

        self._message = message
