# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrderRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, cus_uid: str=None, order_date_time: str=None, p_uid: str=None, message: str=None):  # noqa: E501
        """OrderRequest - a model defined in Swagger

        :param id: The id of this OrderRequest.  # noqa: E501
        :type id: str
        :param cus_uid: The cus_uid of this OrderRequest.  # noqa: E501
        :type cus_uid: str
        :param order_date_time: The order_date_time of this OrderRequest.  # noqa: E501
        :type order_date_time: datetime
        :param p_uid: The p_uid of this OrderRequest.  # noqa: E501
        :type p_uid: str
        :param message: The message of this OrderRequest.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'id': str,
            'cus_uid': str,
            'order_date_time': str,
            'p_uid': str,
            'message': str
        }

        self.attribute_map = {
            'id': 'id',
            'cus_uid': 'cus_uid',
            'order_date_time': 'order_date_time',
            'p_uid': 'p_uid',
            'message': 'message'
        }
        self._id = id
        self._cus_uid = cus_uid
        self._order_date_time = order_date_time
        self._p_uid = p_uid
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'OrderRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Order_Request of this OrderRequest.  # noqa: E501
        :rtype: OrderRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this OrderRequest.


        :return: The id of this OrderRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this OrderRequest.


        :param id: The id of this OrderRequest.
        :type id: str
        """

        self._id = id

    @property
    def cus_uid(self) -> str:
        """Gets the cus_uid of this OrderRequest.

        customer id of the one who placed the order  # noqa: E501

        :return: The cus_uid of this OrderRequest.
        :rtype: str
        """
        return self._cus_uid

    @cus_uid.setter
    def cus_uid(self, cus_uid: str):
        """Sets the cus_uid of this OrderRequest.

        customer id of the one who placed the order  # noqa: E501

        :param cus_uid: The cus_uid of this OrderRequest.
        :type cus_uid: str
        """

        self._cus_uid = cus_uid

    @property
    def order_date_time(self) -> str:
        """Gets the order_date_time of this OrderRequest.


        :return: The order_date_time of this OrderRequest.
        :rtype: datetime
        """
        return self._order_date_time

    @order_date_time.setter
    def order_date_time(self, order_date_time: str):
        """Sets the order_date_time of this OrderRequest.


        :param order_date_time: The order_date_time of this OrderRequest.
        :type order_date_time: datetime
        """

        self._order_date_time = order_date_time

    @property
    def p_uid(self) -> str:
        """Gets the p_uid of this OrderRequest.

        product id of the product ordered  # noqa: E501

        :return: The p_uid of this OrderRequest.
        :rtype: str
        """
        return self._p_uid

    @p_uid.setter
    def p_uid(self, p_uid: str):
        """Sets the p_uid of this OrderRequest.

        product id of the product ordered  # noqa: E501

        :param p_uid: The p_uid of this OrderRequest.
        :type p_uid: str
        """

        self._p_uid = p_uid

    @property
    def message(self) -> str:
        """Gets the message of this OrderRequest.

        email communication b/w customer and contractor  # noqa: E501

        :return: The message of this OrderRequest.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this OrderRequest.

        email communication b/w customer and contractor  # noqa: E501

        :param message: The message of this OrderRequest.
        :type message: str
        """

        self._message = message
